### ISSUE TITLE
"Package python would install , which does not match 2."

### ISSUE THREAD

**Issue by jblaine** [poise/poise-languages#6]
This broke in our dev environment and I can't see how to fix it. It's not clear where the problem lies in the poise stack, so I am reporting it here based on the wording in the error message.

Any thoughts would be welcome.

This is RHEL 7.2.

```
Synchronizing Cookbooks:
  - application_python (4.0.0)
  - application (5.1.0)
  - dmg (2.4.0)
  - r701-chef-vault (0.1.2)
  - mingw (1.2.4)
  - r701-yum (0.2.20)
  - seven_zip (2.0.2)
  - windows (2.0.2)
  - yum-epel (1.0.1)
  - application_git (1.1.0)
  - build-essential (6.0.6)
  - chef-vault (2.0.0)
  - poise-languages (2.0.3)
  - r701-gravatar (0.1.4)
  - git (5.0.1)
  - yum (3.13.0)
  - r701-apache (0.4.80)
  - compat_resource (12.14.6)
  - poise (2.7.1)
  - poise-archive (1.3.0)
  - poise-python (1.5.1)
  - poise-service (1.4.1)
  - logrotate (2.1.0)
...
    * poise_languages_system[python] action install

      ================================================================================
      Error executing action `install` on resource 'poise_languages_system[python]'
      ================================================================================

      PoiseLanguages::Error
      ---------------------
      Package python would install , which does not match 2. Please set the package_name or package_version provider options.

      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:198:in `block (4 levels) in patch_load_current_resource!'
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:193:in `block (3 levels) in patch_load_current_resource!'
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:192:in `tap'
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:192:in `block (2 levels) in patch_load_current_resource!'
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:175:in `block in run_package_action'
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:164:in `each'
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:164:in `run_package_action'
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:100:in `action_install'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
      /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
      /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:45:in `action_install'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb

       32:         poise_languages_system system_package_name do
       33:           # Otherwise use the default install action.
       34:           action(:upgrade) if options['package_upgrade']
       35:           parent new_resource
       36:           # Don't pass true because we want the default computed behavior for that.
       37:           dev_package options['dev_package'] unless options['dev_package'] == true
       38:           dev_package_overrides dev_package_overrides
       39:           package_version options['package_version'] if options['package_version']
       40:           version options['version']
       41:         end
       42:       end
      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb:32:in `install_system_packages'

      poise_languages_system("python") do
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :poise_languages_system
        cookbook_name "r701-gravatar"
        parent # Declared in /var/chef/cache/cookbooks/r701-gravatar/recipes/default.rb:20:in `block in from_file'

      application_python("2") do
        provider PoisePython::PythonProviders::System
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        subresources [application_virtualenv[/gravatar-dev/gravatar-server]]
        declared_type :application_python
        cookbook_name "r701-gravatar"
        recipe_name "default"
        parent application[/gravatar-dev/gravatar-server]
        parent_python nil
        get_pip_url "https://bootstrap.pypa.io/get-pip.py"
        pip_version true
        setuptools_version true
        version "2"
        virtualenv_version true
        wheel_version true
      end

        version "2"
        package_name "python"
        dev_package "python-devel"
      end


    ================================================================================
    Error executing action `install` on resource 'application_python[2]'
    ================================================================================

    PoiseLanguages::Error
    ---------------------
    poise_languages_system[python] (/var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb line 32) had an error: PoiseLanguages::Error: Package python would install , which does not match 2. Please set the package_name or package_version provider options.

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:198:in `block (4 levels) in patch_load_current_resource!'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:193:in `block (3 levels) in patch_load_current_resource!'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:192:in `tap'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:192:in `block (2 levels) in patch_load_current_resource!'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:175:in `block in run_package_action'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:164:in `each'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:164:in `run_package_action'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:100:in `action_install'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
    /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:45:in `action_install'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/r701-gravatar/recipes/default.rb

     20:   python '2' do
     21:     provider :system
     22:   end
     23:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/r701-gravatar/recipes/default.rb:20:in `block in from_file'

    application_python("2") do
      provider PoisePython::PythonProviders::System
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      subresources [application_virtualenv[/gravatar-dev/gravatar-server]]
      declared_type :application_python
      cookbook_name "r701-gravatar"
      recipe_name "default"
      parent application[/gravatar-dev/gravatar-server]
      parent_python nil
      get_pip_url "https://bootstrap.pypa.io/get-pip.py"
      pip_version true
      setuptools_version true
      version "2"
      virtualenv_version true
      wheel_version true
    end
```

**Comment by jblaine** [comment]
I get the same error if I pin poise-languages at any of 1.4.0, 2.0.0, 2.0.1, 2.0.2. I didn't try any others.

**Comment by coderanger** [comment]
What version of Chef?

**Comment by jblaine** [comment]
12.6.0

**Comment by coderanger** [comment]
Any odd package configs or reasons it can't find a version for the `python` package?

**Comment by jblaine** [comment]
Ah HA. Thanks Noah. Our RHEL subscriptions were jacked up.

This works now, though there seems to be room for improvement. The block of code to improve is out of my ruby-league, unfortunately, or I'd submit a patch to make this more intuitive for the next person.

**Comment by GitBytes** [comment]
@coderanger Something else I am noticing with this (Sorry stumbled on this thread and it is kind of down the path of an issue I am dealing with as well..), the variable `repo_name` could be an attribute in the resource so it would work in any subscription based RHEL environment. The specific line being referred to is in `poise-languages/lib/poise_languages/scl/resource.rb` file on line 109. Maybe something like this?
`attribute(:repo_name, kind_of: String, default: 'rhel-server-rhscl-#{node['platform_version'][0]}-rpms')`

This would allow, say `server` in there to be `workstation` or whatever, as is needed in my case but am helpless because of the hardcoding with this and there being an upper level administration of my satellite server so it is not trivial to alter my repo naming scheme.

Not sure if there are other examples of this yet that can be altered but the less hard coding the better in most cases if possible I have found when it comes to actual RHEL systems and planning for things like satellite subscriptions. *That probably goes without saying though I am betting..*

**Comment by coderanger** [comment]
@GitBytes This was about the `:system` provider, not SCLs. SCL repo management is currently a bit busted because the SCL project(s) can't seem to get their shit together and provide a unified product. Unfortunately that change wouldn't fix it entirely, on EC2 the repo needs to be enabled through a different mechanism. There are some other tickets open which cover this. I'm working on getting things fixed, but RH has made it almost impossible to test anything on their OS so I have to rely on user reports as I make changes.

**Comment by coderanger** [comment]
Going to close this because the original issue is resolved. I should probably add a more specific `if empty? raise "no package found"` but that will be later.
